export const rows = [
  {
    id: 1,
    name: "John Doe",
    email: "johndoe@gmail.com",
    age: 25,
    phone: "(111)111-1111",
    access: "Admin",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "janesmith@gmail.com",
    age: 30,
    phone: "(222)222-2222",
    access: "User",
  },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michaelj@gmail.com",
    age: 40,
    phone: "(333)333-3333",
    access: "Manager",
  },
  {
    id: 4,
    name: "Emily Davis",
    email: "emilyd@gmail.com",
    age: 28,
    phone: "(444)444-4444",
    access: "User",
  },
  {
    id: 5,
    name: "David Brown",
    email: "davidb@gmail.com",
    age: 35,
    phone: "(555)555-5555",
    access: "Admin",
  },
  {
    id: 6,
    name: "Sarah Wilson",
    email: "sarahw@gmail.com",
    age: 29,
    phone: "(666)666-6666",
    access: "User",
  },
  {
    id: 7,
    name: "Chris Taylor",
    email: "christ@gmail.com",
    age: 32,
    phone: "(777)777-7777",
    access: "Manager",
  },
  {
    id: 8,
    name: "Rossini Frances",
    email: "rossinifrances@gmail.com",
    age: 36,
    phone: "(222)444-5555",
    access: "User",
  },
  {
    id: 9,
    name: "Harvey Roxie",
    email: "harveyroxie@gmail.com",
    age: 65,
    phone: "(444)555-6239",
    access: "User",
  },
];
