export const rows = [
  {
    id: 1,
    registrarId: 123512,
    name: "Jon Snow",
    age: 35,
    phone: "(665)121-5454",
    email: "jonsnow@gmail.com",
    address: "0912 Won Street, Alabama",
    city: "New York",
    zipCode: 10001,
  },
  {
    id: 2,
    registrarId: 123512,
    name: "Cersei Lannister",
    age: 42,
    phone: "(421)314-2288",
    email: "cerselannister@gmail.com",
    address: "1234 Main Street, New York",
    city: "New York",
    zipCode: 13151,
  },
  {
    id: 3,
    registrarId: 4132513,
    name: "Jaime Lannister",
    age: 45,
    phone: "(422)982-6739",
    email: "jaimelannister@gmail.com",
    address: "3333 Want Blvd, Estanza",
    city: "New York",
    zipCode: 87281,
  },
  {
    id: 4,
    registrarId: 123512,
    name: "Anya Stark",
    age: 16,
    phone: "(921)425-6742",
    email: "anyastark@gmail.com",
    address: "1514 Main Street, New York",
    city: "New York",
    zipCode: 15551,
  },
  {
    id: 5,
    registrarId: 123512,
    name: "Daenerys Targaryen",
    age: 31,
    phone: "(421)445-1189",
    email: "daenerystargaryen@gmail.com",
    address: "11122 Welping Ave, Tenting",
    city: "Tenting",
    zipCode: 14215,
  },
  {
    id: 6,
    registrarId: 123512,
    name: "Ever Melisandre",
    age: 150,
    phone: "(232)545-6483",
    email: "evermelisandre@gmail.com",
    address: "1234 Canvile Street, Esvazark",
    city: "Esvazark",
    zipCode: 10001,
  },
  {
    id: 7,
    registrarId: 123512,
    name: "Ferrara Clifford",
    age: 44,
    phone: "(543)124-0123",
    email: "ferraraclifford@gmail.com",
    address: "22215 Super Street, Everton",
    city: "Everton",
    zipCode: 51523,
  },
  {
    id: 8,
    registrarId: 512315,
    name: "Rossini Frances",
    age: 36,
    phone: "(222)444-5555",
    email: "rossinifrances@gmail.com",
    address: "4123 Ever Blvd, Wentting",
    city: "Esteras",
    zipCode: 44215,
  },
];

export const columns = [
  { field: "id", headerName: "ID", flex: 1, width: 33 },
  { field: "registrarId", headerName: "Registrar ID", flex: 1 },
  { field: "name", headerName: "Name", flex: 1 },
  { field: "age", headerName: "Age", flex: 1, width: 44 },
  { field: "phone", headerName: "Phone Number", flex: 1 },
  { field: "email", headerName: "Email", flex: 1 },
  { field: "address", headerName: "Address", flex: 1 },
  { field: "city", headerName: "City", flex: 1 },
  { field: "zipCode", headerName: "Zip Code", flex: 1 },
];
